project:
  type: website
  output-dir: _site

website:
  title: "R Learning"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: visualize.qmd
        text: Visualization

  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home

      - section: "Data visualization"
        href: visualize.qmd
        contents:
          - href: Visualize/exploratory-data-analysis.qmd
            text: Exploratory Data Analysis
          
          - href: Visualize/communication.qmd
            text: Communication
          
          - href: Visualize/facets.qmd
            text: Facets

          - href: Visualize/statistical-transformation.qmd
            text: Statistical Transformation

          - href: Visualize/position-adjustment.qmd
            text: Position Adjustment

          - href: Visualize/the-layered-grammar-of-graphics.qmd
            text: The Layered Grammar of Graphics
            
        
      - section: "Data transformation"
        href: transform.qmd
        contents:
          - href: Transform/logical-vectors.qmd
            text: Logical Vectors
            
          - href: Transform/numbers.qmd
            text: Numbers
            
format:
  html:
    theme: darkly
    toc: true