project:
  type: website
  output-dir: _site
  render:
    - index.qmd

website:
  title: "R Learning"

  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: darkly
    toc: true